version: 2.1
jobs:
  build-gradle:
    working_directory: ~/app
    docker:
      - image: cimg/openjdk:16.0.2
    steps:
      - checkout:
          path: .
      - run: sudo chmod +x ./gradlew
      - run: ./gradlew assemble
      - run: ./gradlew war
      - run: ./gradlew copyWarFileToTarget
      - store_artifacts:
          path: target
      - persist_to_workspace:
          root: .
          paths:
            - .
    parameters:
      PARAMETERS_PROFILE:
        type: string
        default: env
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: sudo chmod +x ./make_deploy.sh
      - run: ./make_deploy.sh
      - run:
          name: Installing AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run: aws s3 copy ./demo-deploy-zip s3://demo-deploy-wigryz
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

workflows:
  version: 2

  build-demo-deploy:
    jobs:
      - build-gradle:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires: build-gradle
          filters:
            branches:
              only:
                - master