version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.1.1
jobs:
  build-gradle:
    working_directory: ~/appdevtest
    docker:
      - image: cimg/openjdk:16.0.2
    steps:
      - checkout:
          path: ~/appdevtest
      - attach_workspace:
          at: ~/
      - run: sudo chmod +x ./gradlew
#      - run: ./gradlew testClasses
      # - run: ./gradlew test -p domain
      - run: ./gradlew assemble
      - run: ./gradlew war
      - run: ./gradlew copyWarFileToTarget
      - store_artifacts:
          path: target
      - persist_to_workspace:
          root: ~/appdevtest
          paths:
            - target
      - run: sudo chmod +x ./make_deploy.sh
      - run: ./make_deploy.sh
      - aws-s3/copy:
          arguments: '--dryrun'
          from: ~/appdevtest/demo-deploy.zip
          to: s3://demo-deploy-wigryz
    parameters:
      PARAMETERS_PROFILE:
        type: string
        default: env
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

workflows:
  version: 2

  #demo2
  build-demo-deploy:
    jobs:
      - build-gradle:
          filters:
            branches:
              only:
                - master