version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/server
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: "0755"
hooks:
  BeforeInstall:
    - location: scripts/server_clear.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/fix_privileges.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 60
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 60
      runas: ubuntu
