version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/server
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: "0755"
hooks:
  BeforeInstall:
    - location: scripts/server_clear.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/fix_privileges.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 60
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 60
      runas: ec2-user
